"""add_audit_log_and_data_versions

Revision ID: 44ce6d75260c
Revises: 
Create Date: 2026-05-24 21:35:28.170572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ce6d75260c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.String(length=26), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('changed_fields', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('data_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('version_key', sa.String(length=50), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'version_key', name='uq_source_version')
    )
    op.create_index(op.f('ix_data_versions_source'), 'data_versions', ['source'], unique=False)
    op.create_index('ix_clinics_city_dept', 'clinics', ['city', 'is_active'], unique=False)
    op.create_index('ix_clinics_pref_city', 'clinics', ['prefecture', 'city'], unique=False)
    op.create_index('ix_clinics_source_fetched', 'clinics', ['source', 'fetched_at'], unique=False)
    op.add_column('doctors', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('doctors', sa.Column('fetched_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'doctors', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_proc_cat_inv', 'procedures', ['category', 'invasiveness'], unique=False)
    op.create_unique_constraint('uq_proc_name_cat', 'procedures', ['name', 'category'])
    op.create_index('ix_reviews_clinic_source', 'reviews', ['clinic_id', 'source'], unique=False)
    op.create_index('ix_reviews_created', 'reviews', ['created_at'], unique=False)
    op.create_foreign_key(None, 'reviews', 'procedures', ['procedure_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reviews', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index('ix_reviews_created', table_name='reviews')
    op.drop_index('ix_reviews_clinic_source', table_name='reviews')
    op.drop_constraint('uq_proc_name_cat', 'procedures', type_='unique')
    op.drop_index('ix_proc_cat_inv', table_name='procedures')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'fetched_at')
    op.drop_column('doctors', 'source')
    op.drop_index('ix_clinics_source_fetched', table_name='clinics')
    op.drop_index('ix_clinics_pref_city', table_name='clinics')
    op.drop_index('ix_clinics_city_dept', table_name='clinics')
    op.drop_index(op.f('ix_data_versions_source'), table_name='data_versions')
    op.drop_table('data_versions')
    op.drop_index('ix_audit_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_table_record', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
